name: Continuous Integration

on:
  pull_request:
  push:

jobs:
  cache-and-install:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - uses: pnpm/action-setup@v3
      name: Install pnpm
      with:
        version: 8
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install

    - name: Install dependencies (server)
      run: pnpm install
      working-directory: website/server

    - name: Install dependencies (client)
      run: pnpm install
      working-directory: website/client

    - name: Prepare
      run: pnpm run dev:prepare

    - name: Build
      run: pnpm run prepack

    - name: Lint
      run: pnpm run lint

    - name: Run Tests
      run: pnpm run test
